services:
  evolution-api:
    container_name: aman_evolution_api
    image: evoapicloud/evolution-api:v2.3.7
    restart: unless-stopped
    depends_on:
      - evolution-postgres
      - evolution-redis
    ports:
      - "127.0.0.1:8080:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net

  evolution-postgres:
    container_name: aman_evolution_postgres
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: ["postgres", "-c", "max_connections=1000"]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - evolution-net

  evolution-redis:
    container_name: aman_evolution_redis
    image: redis:7
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - evolution-net

volumes:
  evolution_instances:
  postgres_data:
  redis_data:

networks:
  evolution-net:
    driver: bridge
